### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/disposables/CompositeDisposable

### ISSUE THREAD

**Issue by augusWuDotan** [ReactiveX/RxJava#5667]
Version: 2.0.8

Screenshot
[!link] (https://drive.google.com/open?id=0B94Mm0_oaouxaF9KMDBMcmdNMEk)
[!link] (https://drive.google.com/open?id=0B94Mm0_oaouxdDdaai1qRnpXblE)

code
[!link] (https://drive.google.com/open?id=0B94Mm0_oaouxMVdadDYxS29WRE0)

error responce
[!link] (https://drive.google.com/open?id=1GKLLNwfmsY_r4tv6mn89Zwyf0qKG01afE75PUmAdZ8U)

build project OK
in device just have error
can't find this error

**Comment by akarnokd** [comment]
This is probably a multidex problem. Please search StackOverflow for the error class.

**Comment by augusWuDotan** [comment]
when i update Glide version 3.8.0 to 4.2.0
this problem is appear
is it possible Glide 4.2.0 and RxJava with clash

i'll let Glide version  4.2.0 Restore 3.8.0
this problem is temporarily resolved
but There is no real solution

thanks your help  , i'll try  other ways
