### ISSUE TITLE
Problems using rxjava-scala 0.12.3-SNAPSHOT

### ISSUE THREAD

**Issue by cer** [ReactiveX/RxJava#358]
I tried recompiling my code (that worked fine with 0.11.3) with 0.12.3-SNAPSHOT and got quite a few errors. The problems seem related to the covariant changes. I added a couple of tests to RxImplicitsTests.scala that reproduce the similar problems:

```
@Test def testWithChainedMap {
    val observable = Observable.from("1", "2", "3")
    val o2 = observable.map { (s: String) => s + s }.map { (s: String) => s + s }
    assertSubscribeReceives(o2)("1111", "2222")
} 

@Test def testWithBuffer {
    val observable = Observable.from("1", "2", "3")
    val o2 = observable.buffer(2)
    o2.map { (s: java.util.List[String]) => s.size() }
} 
```

These are the compilation errors:

```
[ant:scalac] /Users/cer/3rdPartySrc/RxJava/language-adaptors/rxjava-scala/src/test/scala/rx/lang/scala/RxImplicitsTests.scala:122: error: type mismatch;
[ant:scalac]  found   : String => String
[ant:scalac]  required: rx.util.functions.Func1[_ >: ?0(in value x$1)(in value x$1)(in value x$1)(in value x$1), _ <: ?]
[ant:scalac]         val o2 = observable.map { (s: String) => s + s }.map { (s: String) => s + s }
[ant:scalac]                                                                            ^
[ant:scalac] /Users/cer/3rdPartySrc/RxJava/language-adaptors/rxjava-scala/src/test/scala/rx/lang/scala/RxImplicitsTests.scala:129: error: no type parameters for method map: (x$1: rx.util.functions.Func1[_ >: java.util.List[String], _ <: R])rx.Observable[R] exist so that it can be applied to arguments (rx.util.functions.Func1[java.util.List[String],Int])
[ant:scalac]  --- because ---
[ant:scalac] argument expression's type is not compatible with formal parameter type;
[ant:scalac]  found   : rx.util.functions.Func1[java.util.List[String],Int]
[ant:scalac]  required: rx.util.functions.Func1[_ >: java.util.List[String], _ <: ?R]
[ant:scalac] Note: java.util.List[String] <: Any, but Java-defined trait Func1 is invariant in type T1.
[ant:scalac] You may wish to investigate a wildcard type such as `_ <: Any`. (SLS 3.2.10)
[ant:scalac]         o2.map { (s: java.util.List[String]) => s.size() }
[ant:scalac]            ^
[ant:scalac] /Users/cer/3rdPartySrc/RxJava/language-adaptors/rxjava-scala/src/test/scala/rx/lang/scala/RxImplicitsTests.scala:129: error: type mismatch;
[ant:scalac]  found   : rx.util.functions.Func1[java.util.List[String],Int]
[ant:scalac]  required: rx.util.functions.Func1[_ >: java.util.List[String], _ <: R]
[ant:scalac]         o2.map { (s: java.util.List[String]) => s.size() }
```
